### ISSUE TITLE
Remove/Fix Elixir Submodule

### ISSUE THREAD

**Issue by gkato** [rogerleite/Dotfiles#2]

**Comment by rogerleite** [comment]
Tá quebrado?

**Comment by gkato** [comment]
Ta, por sorte é o ultimo e ele inicia todos os outros submodulos.

Se quiser eu faço isso. Só abri o issue pra ter um reminder

**Comment by rogerleite** [comment]
Manda bala!

**Comment by gkato** [comment]
Done! Arrumei os path do elixir e do fakeclip

**Comment by gkato** [comment]
Dot f*** files ainda fazendo sucesso anos depois...

**Comment by rogerleite** [comment]
:+1:
